<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" total="4" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Navigating to the actitime url]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="24567" started-at="2017-05-02T09:40:27Z" finished-at="2017-05-02T09:40:51Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="24567" started-at="2017-05-02T09:40:27Z" finished-at="2017-05-02T09:40:51Z">
      <class name="com.actitime.scripts.LoginTest">
        <test-method status="PASS" signature="preCondition()[pri:0, instance:com.actitime.scripts.LoginTest@6a41eaa2]" name="preCondition" is-config="true" duration-ms="5939" started-at="2017-05-02T15:10:27Z" finished-at="2017-05-02T15:10:33Z">
          <reporter-output>
            <line>
              <![CDATA[Navigating to the actitime url]]>
            </line>
          </reporter-output>
        </test-method> <!-- preCondition -->
        <test-method status="FAIL" signature="loginTest()[pri:1, instance:com.actitime.scripts.LoginTest@6a41eaa2]" name="loginTest" duration-ms="18612" started-at="2017-05-02T15:10:33Z" finished-at="2017-05-02T15:10:51Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
	at com.sun.proxy.$Proxy7.sendKeys(Unknown Source)
	at com.actitime.pom.LoginPage.login(LoginPage.java:24)
	at com.actitime.scripts.LoginTest.loginTest(LoginTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="postCondition(org.testng.ITestResult)[pri:0, instance:com.actitime.scripts.LoginTest@6a41eaa2]" name="postCondition" is-config="true" duration-ms="0" started-at="2017-05-02T15:10:51Z" finished-at="2017-05-02T15:10:51Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[wrong number of arguments]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:220)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
      </class> <!-- com.actitime.scripts.LoginTest -->
      <class name="com.actitime.scripts.CreateCustAndProjTest">
        <test-method status="SKIP" signature="preCondition()[pri:0, instance:com.actitime.scripts.CreateCustAndProjTest@7cd62f43]" name="preCondition" is-config="true" duration-ms="0" started-at="2017-05-02T15:10:51Z" finished-at="2017-05-02T15:10:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondition -->
        <test-method status="SKIP" signature="createCustomerTest()[pri:1, instance:com.actitime.scripts.CreateCustAndProjTest@7cd62f43]" name="createCustomerTest" duration-ms="1" started-at="2017-05-02T15:10:51Z" finished-at="2017-05-02T15:10:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createCustomerTest -->
        <test-method status="SKIP" signature="createProjectTest()[pri:2, instance:com.actitime.scripts.CreateCustAndProjTest@7cd62f43]" name="createProjectTest" duration-ms="1" started-at="2017-05-02T15:10:51Z" finished-at="2017-05-02T15:10:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createProjectTest -->
        <test-method status="SKIP" signature="deleteCustomerTest()[pri:3, instance:com.actitime.scripts.CreateCustAndProjTest@7cd62f43]" name="deleteCustomerTest" duration-ms="1" started-at="2017-05-02T15:10:51Z" finished-at="2017-05-02T15:10:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCustomerTest -->
        <test-method status="SKIP" signature="postCondition(org.testng.ITestResult)[pri:0, instance:com.actitime.scripts.CreateCustAndProjTest@7cd62f43]" name="postCondition" is-config="true" duration-ms="0" started-at="2017-05-02T15:10:51Z" finished-at="2017-05-02T15:10:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCondition -->
      </class> <!-- com.actitime.scripts.CreateCustAndProjTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
